# Generated by Django 2.1.5 on 2019-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='study', max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
