# Generated by Django 2.1.5 on 2019-03-24 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recrod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.IntegerField(default=1)),
                ('startpage', models.IntegerField(default=1)),
                ('endpage', models.IntegerField(default=1)),
                ('words', models.IntegerField()),
                ('readingnotes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
