# Generated by Django 2.1.5 on 2019-03-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingnotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recrod',
            old_name='bookname',
            new_name='book_name',
        ),
    ]
