# Generated by Django 2.1.5 on 2019-03-24 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readingnotes', '0002_auto_20190324_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recrod',
            new_name='Record',
        ),
    ]
